CREATE TABLE `StoreProduct` (
  `id` BIGINT,
  `title` VARCHAR(1024),
  `type` VARCHAR(1024),
  `description` VARCHAR(1024),
  `filename` VARCHAR(1024),
  `height` BIGINT,
  `width` BIGINT,
  `price` DOUBLE,
  `rating` BIGINT,
  `category` VARCHAR(1024) NULL
);

INSERT INTO `storeproducts` (title, type, description, filename, height, width, price, rating, category) VALUES 
('Brown eggs','dairy','Raw organic brown eggs in a basket','0.jpg',600,400,28.1,4,'PopularItem'),
('Sweet fresh stawberry','fruit','Sweet fresh stawberry on the wooden table','1.jpg',450,299,29.45,4,'PopularItem'),
('Asparagus','vegetable','Asparagus with ham on the wooden table','2.jpg',450,299,18.95,3,'PopularItem'),
('Green smoothie','dairy','Glass of green smoothie with quail egg''s yolk, served with cocktail tube, green apple and baby spinach leaves over tin surface.','3.jpg',600,399,17.68,4,'PopularItem'),
('Raw legums','vegetable','Raw legums on the wooden table','4.jpg',450,299,17.11,2,'NewArrival'),
('Baking cake','dairy','Baking cake in rural kitchen - dough  recipe ingredients (eggs, flour, sugar) on vintage wooden table from above.','5.jpg',450,675,11.14,4,'PopularItem'),
('Pesto with basil','vegetable','Italian traditional pesto with basil, chesse and oil','6.jpg',450,299,18.19,2,'NewArrival'),
('Hazelnut in black ceramic bowl','vegetable','Hazelnut in black ceramic bowl on old wooden background. forest wealth. rustic style. selective focus','7.jpg',450,301,27.35,0,NULL),
('Fresh stawberry','fruit','Sweet fresh stawberry on the wooden table','8.jpg',600,399,28.59,4,'PopularItem'),
('Lemon and salt','fruit','Rosemary, lemon and salt on the table','9.jpg',450,299,15.79,5,NULL),
('Homemade bread','bakery','Homemade bread','10.jpg',450,301,17.48,3,NULL),
('Legums','vegetable','Cooked legums on the wooden table','11.jpg',600,399,14.77,0,NULL),
('Fresh tomato','vegetable','Fresh tomato juice with basil','12.jpg',600,903,16.3,2,'NewArrival'),
('Healthy breakfast','fruit','Healthy breakfast set. rice cereal or porridge with berries and honey over rustic wood background','13.jpg',450,350,13.02,2,'NewArrival'),
('Green beans','vegetable','Raw organic green beans ready to eat','14.jpg',450,300,28.79,1,NULL),
('Baked stuffed portabello mushrooms','bakery','Homemade baked stuffed portabello mushrooms with spinach and cheese','15.jpg',600,400,20.31,1,NULL),
('Strawberry jelly','fruit','Homemade organic strawberry jelly in a jar','16.jpg',400,600,14.18,1,NULL),
('Pears juice','fruit','Fresh pears juice on the wooden table','17.jpg',600,398,19.49,4,'PopularItem'),
('Fresh pears','fruit','Sweet fresh pears on the wooden table','18.jpg',600,398,15.12,5,NULL),
('Caprese salad','vegetable','Homemade healthy caprese salad with tomato mozzarella and basil','19.jpg',400,600,16.76,5,NULL),
('Oranges','fruit','Orange popsicle ice cream bars made from fresh oranges.  a refreshing summer treat.','20.jpg',450,274,21.48,4,'PopularItem'),
('Vegan food','vegetable','Concept of vegan food','21.jpg',450,299,29.66,4,'PopularItem'),
('Breakfast with muesli','dairy','Concept of healthy breakfast with muesli','22.jpg',450,299,22.7,2,'NewArrival'),
('Honey','bakery','Honey and honeycell on the table','23.jpg',450,299,17.01,2,'NewArrival'),
('Breakfast with cottage','fruit','Healthy breakfast with cottage cheese and strawberry','24.jpg',600,398,14.05,1,NULL),
('Strawberry smoothie','fruit','Glass of red strawberry smoothie with chia seeds, served with retro cocktail tube, fresh mint and strawberries over dark background','25.jpg',600,400,28.86,2,'NewArrival'),
('Strawberry and mint','fruit','Homemade muesli with strawberry and mint','26.jpg',450,299,26.21,4,'PopularItem'),
('Ricotta','dairy','Ricotta with berry and mint','27.jpg',600,398,27.81,5,NULL),
('Cuban sandwiche','bakery','Homemade traditional cuban sandwiches with ham pork and cheese','28.jpg',450,300,18.5,4,'PopularItem'),
('Granola','dairy','Glass jar with homemade granola and yogurt with nuts, raspberries and blackberries on wooden cutting board over white textile in day light','29.jpg',450,300,29.97,3,NULL),
('Smoothie with chia seeds','fruit','Glass of red strawberry smoothie with chia seeds, served with retro cocktail tube, fresh mint and strawberries over wooden table','30.jpg',600,900,25.26,5,NULL),
('Yogurt','dairy','Homemade yogurt with raspberry and mint','31.jpg',450,299,27.61,4,'PopularItem'),
('Sandwich with salad','vegetable','Vegan sandwich with salad, tomato and radish','32.jpg',600,398,22.48,5,NULL),
('Cherry','fruit','Cherry with sugar on old table','33.jpg',600,400,14.35,5,NULL),
('Raw asparagus','vegetable','Raw fresh asparagus salad with cheese and dressing','34.jpg',600,400,22.97,4,'PopularItem'),
('Corn','vegetable','Grilled corn on the cob with salt and butter','35.jpg',450,300,13.55,2,'NewArrival'),
('Vegan','vegan','Concept of healthy vegan eating','36.jpg',600,398,28.96,5,NULL),
('Fresh blueberries','fruit','Healthy breakfast. berry crumble with fresh blueberries, raspberries, strawberries, almond, walnuts, pecans, yogurt, and mint in ceramic plates over white wooden surface, top view','37.jpg',450,321,21.01,4,'PopularItem'),
('Smashed avocado','fruit','Vegan sandwiches with smashed avocado, tomatoes and radish. top view','38.jpg',450,450,25.88,0,NULL),
('Italian ciabatta','bakery','Italian ciabatta bread cut in slices on wooden chopping board with herbs, garlic and olives over dark grunge backdrop, top view','39.jpg',450,565,15.18,1,NULL),
('Rustic breakfast','dairy','Rustic healthy breakfast set. cooked buckwheat groats with milk and honey on dark grunge backdrop. top view, copy space','40.jpg',450,307,21.32,0,NULL),
('Sliced lemons','fruit','Heap of whole and sliced lemons and limes with mint in vintage metal grid box over old wooden table with turquoise wooden background. dark rustic style.','41.jpg',600,900,27.14,2,'NewArrival'),
('Plums','fruit','Yellow and red sweet plums','42.jpg',450,299,19.18,1,NULL),
('French fries','bakery','Homemade oven baked french fries with ketchup','43.jpg',600,400,18.32,3,NULL),
('Strawberries','fruit','Healthy breakfast set. rice cereal or porridge with fresh strawberry, apricots, almond and honey over white rustic wood backdrop, top view.','44.jpg',450,352,15.13,3,NULL),
('Ground beef meat burger','meat','Raw ground beef meat burger steak cutlets with seasoning on vintage wooden boards, black background','45.jpg',450,675,11.73,5,NULL),
('Tomatoes','fruit','Organic tomatoes made with love','46.jpg',450,675,26.03,4,'PopularItem'),
('Basil','vegetable','Concept of vegan food with basil','47.jpg',450,678,15.19,4,'PopularItem'),
('Fruits bouquet','fruit','Abstract citrus fruits bouquet on blue background','48.jpg',600,401,18.18,1,NULL),
('Peaches on branch','fruit','Peaches on branch with leaves and glasses with peach juice and limonade with ice cubes in aluminum tray over old metal table. dark rustic style. top view.','49.jpg',600,400,25.62,3,NULL);

